export const seedCategories = [
  "Спідниці & сукні",
  "Сорочки & верх",
  "Аксесуари",
];

export const seedReviews = [
  {
    id: "seed-review-1",
    name: "Марина",
    text: "Замовляла спідницю з деніму — сіла ідеально по фігурі, і досі ловлю питання, де купила.",
    image: "",
    createdAt: "2026-02-01T10:00:00.000Z",
  },
  {
    id: "seed-review-2",
    name: "Аня",
    text: "Сорочка вийшла краще, ніж на фото. Виктория тримала в курсі на кожному етапі пошиття.",
    image: "",
    createdAt: "2026-02-05T10:00:00.000Z",
  },
];

export const seedProducts = [
  {
    id: "seed-skirt-denim",
    title: "Печворк-спідниця з деніму",
    category: "Спідниці & сукні",
    price: 1400,
    inStock: true,
    description: "Асиметрична спідниця-максі з фрагментів старого деніму.",
    details:
      "Асиметрична спідниця максі, зібрана з фрагментів старого деніму різних відтінків. Кожен фрагмент — окрема історія тканини. Носиться високо на талії, добре тримає форму.",
    fabric: "Денім (100% бавовна), бавовняна підкладка",
    sizes: "M (46), обхват талії 70–76 см",
    images: [],
    swatch: "denim",
    accent: "#2a3a52",
    waterLiters: 7500,
    fabricKg: 0.6,
    co2Kg: 9,
    createdAt: "2026-01-10T10:00:00.000Z",
  },
  {
    id: "seed-dress-denim",
    title: "Сукня-трансформер із залишків сорочок",
    category: "Спідниці & сукні",
    price: 1900,
    inStock: false,
    description: "Сукня-міді з комбінованих тканин, дві довжини на вибір.",
    details:
      "Пошита з фрагментів чоловічих сорочок і скатертин. М'яка бавовна, вільний силует, кишені. Довжину можна скоригувати під замовлення.",
    fabric: "Бавовна, льон",
    sizes: "S (42–44)",
    images: [],
    swatch: "denim",
    accent: "#3a4a5c",
    waterLiters: 5200,
    fabricKg: 0.5,
    co2Kg: 7,
    createdAt: "2026-01-14T10:00:00.000Z",
  },
  {
    id: "seed-shirt-color-block",
    title: "Оверсайз-сорочка колор-блок",
    category: "Сорочки & верх",
    price: 1800,
    inStock: true,
    description: "Оверсайз-сорочка з контрастною вставкою іншої фактури.",
    details:
      "Класичний крій сорочки, доведений до оверсайзу, з контрастною вставкою з іншої тканини. Довжина рукава та посадка коригуються під ваш зріст.",
    fabric: "Бавовняна поплінова тканина",
    sizes: "L (48–50)",
    images: [],
    swatch: "shirt",
    accent: "#b9764a",
    waterLiters: 3800,
    fabricKg: 0.4,
    co2Kg: 5,
    createdAt: "2026-01-18T10:00:00.000Z",
  },
  {
    id: "seed-vest-patchwork",
    title: "Жилет-печворк",
    category: "Сорочки & верх",
    price: 1600,
    inStock: true,
    description: "Легкий жилет із фрагментів вовняних та бавовняних тканин.",
    details:
      "Універсальний жилет прямого крою, який добре поєднується і з сукнею, і з джинсами. Підкладка з натуральної бавовни.",
    fabric: "Вовна / бавовна (мікс за наявністю)",
    sizes: "M/L (46–48)",
    images: [],
    swatch: "shirt",
    accent: "#8a5a3c",
    waterLiters: 4100,
    fabricKg: 0.35,
    co2Kg: 6,
    createdAt: "2026-01-22T10:00:00.000Z",
  },
  {
    id: "seed-denim-pouch",
    title: "Космметичка з деніму «Million X»",
    category: "Аксесуари",
    price: 350,
    inStock: true,
    description: "Космметичка-косметичка з апсайкл-деніму зі шкіряним патчем і зав'язкою.",
    details:
      "Пошита з фрагмента вживаних джинсів — збережена оригінальна фурнітура, шкіряний патч і латунна блискавка. Компактна, тримає форму завдяки щільній підкладці.",
    fabric: "Денім (100% бавовна), підкладка",
    sizes: "13 × 8 × 6 см",
    images: ["/uploads/seed-denim-pouch-1.jpg", "/uploads/seed-denim-pouch-2.jpg"],
    swatch: "denim",
    accent: "#2a3a52",
    waterLiters: 2600,
    fabricKg: 0.15,
    co2Kg: 2,
    createdAt: "2026-01-25T10:00:00.000Z",
  },
  {
    id: "seed-butterfly-pouch-set",
    title: "Набір космметичок «Метелик»",
    category: "Аксесуари",
    price: 420,
    inStock: true,
    description: "Дві косметички з ручною вишивкою метелика — велика та маленька.",
    details:
      "Комплект із двох косметичок з бавовняної тканини з вишивкою метелика і квітів. Підкладка в дрібну квіточку, міцна блискавка. Велика — під косметику, маленька — під дрібниці чи навушники.",
    fabric: "Бавовна, підкладка-бязь",
    sizes: "Велика 20 × 13 см, мала 16 × 8 см",
    images: [
      "/uploads/seed-butterfly-pouch-1.jpg",
      "/uploads/seed-butterfly-pouch-2.jpg",
      "/uploads/seed-butterfly-pouch-3.jpg",
    ],
    swatch: "scrunchie",
    accent: "#c9739a",
    waterLiters: 1800,
    fabricKg: 0.12,
    co2Kg: 1.5,
    createdAt: "2026-01-27T10:00:00.000Z",
  },
];
